In [122]:
import json
import pandas as pd
import numpy as np
import networkx as nx

## Max Flow Validation

In [132]:
with open("training_data_max_flow.json", "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

df.groupby(
    ["n_nodes", "n_arcs", "density", "attack_limit"]
).size().unstack(fill_value=0)

attack_limit              1   2   3   4   5
n_nodes n_arcs density
30      75     2.500000  50  50  50  50  50
        120    4.000000  50  50  50  50  50
        180    6.000000  50  50  50  50  50
50      125    2.500000  50  50  50  50  50
        200    4.000000  50  50  50  50  50
        300    6.000000  50  50  50  50  50
75      188    2.506667  50  50  50  50  50
        300    4.000000  50  50  50  50  50
        450    6.000000  50  50  50  50  50

In [134]:
counts = (
    df.groupby(["n_nodes", "n_arcs", "attack_limit"])
      .size()
      .reset_index(name="count")
)

counts

    n_nodes  n_arcs  attack_limit  count
0        30      75             1     50
1        30      75             2     50
2        30      75             3     50
3        30      75             4     50
4        30      75             5     50
5        30     120             1     50
6        30     120             2     50
7        30     120             3     50
8        30     120             4     50
9        30     120             5     50
10       30     180             1     50
11       30     180             2     50
12       30     180             3     50
13       30     180             4     50
14       30     180             5     50
15       50     125             1     50
16       50     125             2     50
17       50     125             3     50
18       50     125             4     50
19       50     125             5     50
20       50     200             1     50
21       50     200             2     50
22       50     200             3     50
23       50     200             4     50
24       50     200             5     50
25       50     300             1     50
26       50     300             2     50
27       50     300             3     50
28       50     300             4     50
29       50     300             5     50
30       75     188             1     50
31       75     188             2     50
32       75     188             3     50
33       75     188             4     50
34       75     188             5     50
35       75     300             1     50
36       75     300             2     50
37       75     300             3     50
38       75     300             4     50
39       75     300             5     50
40       75     450             1     50
41       75     450             2     50
42       75     450             3     50
43       75     450             4     50
44       75     450             5     50

In [136]:
data[0].keys()

dict_keys(['n_nodes', 'n_arcs', 'density', 'source', 'sink', 'attack_limit', 'problem_type', 'u', 'v', 'penalty', 'attack', 'max_flow', 'penalty_high', 'mip_solve_time', 'solver_status', 'termination_condition', 'capacity', 'capacity_high', 'baseline_max_flow', 'graph_seed', 'replication', 'attack_budget'])

In [138]:
instance = data[0]

G = nx.DiGraph()

for u, v, capacity in zip(
    instance["u"],
    instance["v"],
    instance["capacity"]
):
    G.add_edge(
        u,
        v,
        capacity=capacity
    )

source = instance["source"]
sink = instance["sink"]

baseline = nx.maximum_flow_value(
    G,
    source,
    sink,
    capacity="capacity"
)

print("Recomputed baseline:", baseline)
print("Saved baseline:", instance["baseline_max_flow"])

Recomputed baseline: 42
Saved baseline: 42.0

In [140]:
G_interdicted = G.copy()

for u, v, attack in zip(
    instance["u"],
    instance["v"],
    instance["attack"]
):
    if attack == 1:
        G_interdicted.remove_edge(u, v)

interdicted_flow = nx.maximum_flow_value(
    G_interdicted,
    source,
    sink,
    capacity="capacity"
)

print("Recomputed interdicted flow:", interdicted_flow)
print("Saved MIP objective:", instance["max_flow"])

Recomputed interdicted flow: 31
Saved MIP objective: 31.0

In [142]:
results = []

for i, instance in enumerate(data):

    G = nx.DiGraph()

    for u, v, capacity in zip(
        instance["u"],
        instance["v"],
        instance["capacity"]
    ):
        G.add_edge(
            u,
            v,
            capacity=capacity
        )

    source = instance["source"]
    sink = instance["sink"]

    baseline = nx.maximum_flow_value(
        G,
        source,
        sink,
        capacity="capacity"
    )

    G_interdicted = G.copy()

    for u, v, attack in zip(
        instance["u"],
        instance["v"],
        instance["attack"]
    ):
        if attack == 1:
            G_interdicted.remove_edge(u, v)

    attacked = nx.maximum_flow_value(
        G_interdicted,
        source,
        sink,
        capacity="capacity"
    )

    saved = instance["max_flow"]

    results.append({
        "index": i,
        "graph_seed": instance["graph_seed"],
        "attack_limit": instance["attack_limit"],
        "density": instance["density"],
        "baseline": baseline,
        "recomputed_objective": attacked,
        "saved_objective": saved,
        "matches": np.isclose(attacked, saved)
    })

check_df = pd.DataFrame(results)

In [144]:
check_df["matches"].value_counts()

matches
True    2250
Name: count, dtype: int64

In [148]:
check_df["flow_reduction"] = (
    check_df["baseline"]
    - check_df["recomputed_objective"]
)

check_df["relative_flow_reduction"] = (
    check_df["flow_reduction"]
    / check_df["baseline"]
)

In [150]:
check_df.groupby("attack_limit").agg(
    avg_baseline=("baseline", "mean"),
    avg_residual_flow=("recomputed_objective", "mean"),
    avg_flow_reduction=("flow_reduction", "mean"),
    avg_relative_reduction=("relative_flow_reduction", "mean")
)

,avg_baseline,avg_residual_flow,avg_flow_reduction,avg_relative_reduction
attack_limit,,,,
1,58.024444,41.686667,16.337778,0.294120
2,58.024444,28.404444,29.620000,0.527645
3,58.024444,17.804444,40.220000,0.709148
4,58.024444,9.795556,48.228889,0.843802
5,58.024444,4.331111,53.693333,0.933330

In [152]:
violations = []

for seed, group in check_df.groupby("graph_seed"):

    group = group.sort_values("attack_limit")

    objectives = np.round(
        group["saved_objective"].to_numpy(),
        6
    )

    # max-flow objective should not increase as K increases
    if np.any(np.diff(objectives) > 0):
        violations.append(seed)

print("Monotonicity violations:", len(violations))

Monotonicity violations: 0

## Shortest Path Validation

In [29]:
with open("training_data_shortest_path.json", "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

In [48]:
baseline_disconnected = []

for instance in data:
    G = nx.DiGraph()

    G.add_nodes_from(range(instance["n_nodes"]))

    for u, v, dist in zip(
        instance["u"],
        instance["v"],
        instance["dist"]
    ):
        G.add_edge(u, v, weight=dist)

    baseline_disconnected.append(
        not nx.has_path(
            G,
            instance["source"],
            instance["sink"]
        )
    )

print("Baseline disconnected rate:")
print(np.mean(baseline_disconnected))

Baseline disconnected rate:
0.0

In [54]:
instance = data[0]

G = nx.DiGraph()

for u, v, dist in zip(
    instance["u"],
    instance["v"],
    instance["dist"]
):
    G.add_edge(u, v, weight=dist)

source = instance["source"]
sink = instance["sink"]

baseline = nx.shortest_path_length(
    G,
    source,
    sink,
    weight="weight"
)

print("Recomputed baseline:", baseline)
print("Saved baseline:", instance["path_length"])

Recomputed baseline: 6
Saved baseline: 12.0

In [56]:
G_interdicted = nx.DiGraph()

for u, v, dist, penalty, attack in zip(
    instance["u"],
    instance["v"],
    instance["dist"],
    instance["penalty"],
    instance["attack"]
):
    new_dist = dist + penalty * attack

    G_interdicted.add_edge(
        u,
        v,
        weight=new_dist
    )

interdicted_length = nx.shortest_path_length(
    G_interdicted,
    source,
    sink,
    weight="weight"
)

print("Baseline shortest path:", baseline)
print("Recomputed interdicted path:", interdicted_length)
print("Saved MIP path_length:", instance["path_length"])

Baseline shortest path: 6
Recomputed interdicted path: 12
Saved MIP path_length: 12.0

In [58]:
results = []

for i, instance in enumerate(data):

    G = nx.DiGraph()
    G_interdicted = nx.DiGraph()

    for u, v, dist, penalty, attack in zip(
        instance["u"],
        instance["v"],
        instance["dist"],
        instance["penalty"],
        instance["attack"]
    ):
        # Original graph
        G.add_edge(
            u,
            v,
            weight=dist
        )

        # Same graph after interdiction penalties
        G_interdicted.add_edge(
            u,
            v,
            weight=dist + penalty * attack
        )

    source = instance["source"]
    sink = instance["sink"]

    baseline = nx.shortest_path_length(
        G,
        source,
        sink,
        weight="weight"
    )

    attacked = nx.shortest_path_length(
        G_interdicted,
        source,
        sink,
        weight="weight"
    )

    results.append({
        "index": i,
        "graph_seed": instance["graph_seed"],
        "attack_limit": instance["attack_limit"],
        "baseline": baseline,
        "recomputed_objective": attacked,
        "saved_objective": instance["path_length"],
        "matches": np.isclose(
            attacked,
            instance["path_length"]
        )
    })

check_df = pd.DataFrame(results)

In [60]:
check_df["matches"].value_counts()

matches
True    2250
Name: count, dtype: int64

In [62]:
check_df["path_increase"] = (
    check_df["recomputed_objective"] -
    check_df["baseline"]
)

check_df["relative_path_increase"] = (
    check_df["path_increase"] /
    check_df["baseline"]
)

In [64]:
check_df.groupby("attack_limit").agg(
    avg_baseline=("baseline", "mean"),
    avg_interdicted=("recomputed_objective", "mean"),
    avg_path_increase=("path_increase", "mean"),
    avg_relative_increase=("relative_path_increase", "mean")
)

,avg_baseline,avg_interdicted,avg_path_increase,avg_relative_increase
attack_limit,,,,
1,13.651111,18.122222,4.471111,0.485561
2,13.651111,20.951111,7.300000,0.730154
3,13.651111,22.926667,9.275556,0.885688
4,13.651111,24.584444,10.933333,1.018333
5,13.651111,25.795556,12.144444,1.115512

In [52]:
instance.keys()

dict_keys(['n_nodes', 'n_arcs', 'density', 'source', 'sink', 'attack_limit', 'problem_type', 'u', 'v', 'penalty', 'attack', 'path_length', 'penalty_high', 'mip_solve_time', 'solver_status', 'termination_condition', 'dist', 'cost_high', 'graph_seed', 'replication', 'attack_budget'])

In [88]:
negative_diffs = []

for seed, group in check_df.groupby("graph_seed"):
    group = group.sort_values("attack_limit")

    objectives = group["saved_objective"].to_numpy()
    ks = group["attack_limit"].to_numpy()
    diffs = np.diff(objectives)

    for i, diff in enumerate(diffs):
        if diff < 0:
            negative_diffs.append({
                "graph_seed": seed,
                "from_K": ks[i],
                "to_K": ks[i + 1],
                "from_objective": objectives[i],
                "to_objective": objectives[i + 1],
                "difference": diff
            })

negative_df = pd.DataFrame(negative_diffs)

negative_df.sort_values("difference")

   graph_seed  from_K  to_K  from_objective  to_objective    difference
0     5012521       4     5            47.0          47.0 -2.756742e-07

In [76]:
violations

[5012521]

In [78]:
bad_seed = violations[0]

check_df[
    check_df["graph_seed"] == bad_seed
].sort_values("attack_limit")

,index,graph_seed,attack_limit,baseline,recomputed_objective,saved_objective,matches,path_increase,relative_path_increase
170,170,5012521,1,32,38,38.0,True,6,0.18750
620,620,5012521,2,32,42,42.0,True,10,0.31250
1070,1070,5012521,3,32,44,44.0,True,12,0.37500
1520,1520,5012521,4,32,47,47.0,True,15,0.46875
1970,1970,5012521,5,32,47,47.0,True,15,0.46875

## Min Cost Flow Validation

In [90]:
with open("training_data_min_cost_flow.json", "r") as f:
    data = json.load(f)

instance = data[0]

instance.keys()

dict_keys(['n_nodes', 'n_arcs', 'density', 'source', 'sink', 'attack_limit', 'problem_type', 'u', 'v', 'penalty', 'attack', 'min_cost_flow', 'penalty_high', 'mip_solve_time', 'solver_status', 'termination_condition', 'dist', 'cost_high', 'capacity', 'capacity_high', 'flow_demand', 'graph_seed', 'replication', 'attack_budget'])

In [106]:
instance = data[0]

G = nx.DiGraph()

for u, v, cost, capacity in zip(
    instance["u"],
    instance["v"],
    instance["dist"],
    instance["capacity"]
):
    G.add_edge(
        u,
        v,
        weight=cost,
        capacity=capacity
    )

source = instance["source"]
sink = instance["sink"]
flow_demand = instance["flow_demand"]

# NetworkX convention:
# negative demand = supply
# positive demand = demand
for node in G.nodes():
    G.nodes[node]["demand"] = 0

G.nodes[source]["demand"] = -flow_demand
G.nodes[sink]["demand"] = flow_demand

baseline = nx.min_cost_flow_cost(
    G,
    demand="demand",
    capacity="capacity",
    weight="weight"
)

print("Recomputed baseline cost:", baseline)

Recomputed baseline cost: 36

In [108]:
G_interdicted = nx.DiGraph()

for u, v, cost, capacity, penalty, attack in zip(
    instance["u"],
    instance["v"],
    instance["dist"],
    instance["capacity"],
    instance["penalty"],
    instance["attack"]
):
    interdicted_cost = cost + penalty * attack

    G_interdicted.add_edge(
        u,
        v,
        weight=interdicted_cost,
        capacity=capacity
    )

for node in G_interdicted.nodes():
    G_interdicted.nodes[node]["demand"] = 0

G_interdicted.nodes[source]["demand"] = -flow_demand
G_interdicted.nodes[sink]["demand"] = flow_demand

attacked = nx.min_cost_flow_cost(
    G_interdicted,
    demand="demand",
    capacity="capacity",
    weight="weight"
)

print("Baseline cost:", baseline)
print("Recomputed interdicted cost:", attacked)
print("Saved MIP objective:", instance["min_cost_flow"])

Baseline cost: 36
Recomputed interdicted cost: 72
Saved MIP objective: 72.0

In [110]:
results = []

for i, instance in enumerate(data):

    G = nx.DiGraph()
    G_interdicted = nx.DiGraph()

    for u, v, cost, capacity, penalty, attack in zip(
        instance["u"],
        instance["v"],
        instance["dist"],
        instance["capacity"],
        instance["penalty"],
        instance["attack"]
    ):

        G.add_edge(
            u,
            v,
            weight=cost,
            capacity=capacity
        )

        G_interdicted.add_edge(
            u,
            v,
            weight=cost + penalty * attack,
            capacity=capacity
        )

    source = instance["source"]
    sink = instance["sink"]
    flow_demand = instance["flow_demand"]

    for node in G.nodes():
        G.nodes[node]["demand"] = 0
        G_interdicted.nodes[node]["demand"] = 0

    G.nodes[source]["demand"] = -flow_demand
    G.nodes[sink]["demand"] = flow_demand

    G_interdicted.nodes[source]["demand"] = -flow_demand
    G_interdicted.nodes[sink]["demand"] = flow_demand

    baseline = nx.min_cost_flow_cost(
        G,
        demand="demand",
        capacity="capacity",
        weight="weight"
    )

    attacked = nx.min_cost_flow_cost(
        G_interdicted,
        demand="demand",
        capacity="capacity",
        weight="weight"
    )

    saved = instance["min_cost_flow"]

    results.append({
        "index": i,
        "graph_seed": instance["graph_seed"],
        "attack_limit": instance["attack_limit"],
        "baseline": baseline,
        "recomputed_objective": attacked,
        "saved_objective": saved,
        "matches": np.isclose(attacked, saved)
    })

check_df = pd.DataFrame(results)

In [112]:
check_df["matches"].value_counts()

matches
True    2250
Name: count, dtype: int64

In [116]:
check_df["cost_increase"] = (
    check_df["recomputed_objective"]
    - check_df["baseline"]
)

check_df["relative_cost_increase"] = (
    check_df["cost_increase"]
    / check_df["baseline"]
)

In [118]:
check_df.groupby("attack_limit").agg(
    avg_baseline=("baseline", "mean"),
    avg_interdicted=("recomputed_objective", "mean"),
    avg_cost_increase=("cost_increase", "mean"),
    avg_relative_increase=("relative_cost_increase", "mean")
)

,avg_baseline,avg_interdicted,avg_cost_increase,avg_relative_increase
attack_limit,,,,
1,217.068889,266.473333,49.404444,0.301675
2,217.068889,299.808889,82.740000,0.480546
3,217.068889,325.771111,108.702222,0.614866
4,217.068889,345.515556,128.446667,0.714200
5,217.068889,362.468889,145.400000,0.797616

In [120]:
violations = []

for seed, group in check_df.groupby("graph_seed"):

    group = group.sort_values("attack_limit")

    # Your costs/penalties are integer-valued, so round away
    # solver floating-point noise before checking monotonicity.
    objectives = np.round(
        group["saved_objective"].to_numpy()
    )

    if np.any(np.diff(objectives) < 0):
        violations.append(seed)

print("Monotonicity violations:", len(violations))

Monotonicity violations: 0