In [23]:
import json
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [25]:
pd.set_option('display.max_columns',None)

In [27]:
# Load JSON

def load_json(path):
    with open(path, "r") as f:
        return json.load(f)

In [29]:
def count_shortest_paths(G, source, sink, weight="weight"):

    predecessors, distances = nx.dijkstra_predecessor_and_distance(G, source, weight=weight)

    if sink not in distances:
        return 0

    # Dijkstra distances give a topological ordering of the
    # shortest-path DAG when edge weights are positive.
    nodes = sorted(distances, key=distances.get)

    path_counts = {node: 0 for node in nodes}
    path_counts[source] = 1

    for node in nodes:

        if node == source:
            continue

        path_counts[node] = sum(path_counts[pred] for pred in predecessors[node])

    return path_counts[sink]

In [95]:
# Extract one row of graph-level characteristics

def graph_characteristics(sample, dataset_name):
    
    n = sample["n_nodes"]
    m = sample["n_arcs"]

    u = sample["u"]
    v = sample["v"]
    dist = sample["dist"]

    source = sample["source"]
    sink = sample["sink"]

    # Build directed graph using original edge costs
    G = nx.DiGraph()

    for ui, vi, di in zip(u, v, dist):
        G.add_edge(ui, vi, weight=di)

    # Degree characteristics
    in_degrees = np.array([d for _, d in G.in_degree()])
    out_degrees = np.array([d for _, d in G.out_degree()])
    total_degrees = np.array([d for _, d in G.degree()])
    
    # Degree concentration
    std_in_degree = in_degrees.std()
    std_out_degree = out_degrees.std()
    max_in_degree = in_degrees.max()
    max_out_degree = out_degrees.max()

    # Source-to-sink edge connectivity
    # Maximum number of edge-disjoint directed s-t paths
    edge_connectivity = nx.edge_connectivity(G, source, sink)

    # Source-to-sink relevant arcs
    # An arc (u,v) is relevant if there is an s-t path through it
    reachable_from_source = nx.descendants(G, source) | {source}
    can_reach_sink = nx.ancestors(G, sink) | {sink}

    relevant_arcs = [
        (u, v) for u, v in G.edges()
        if u in reachable_from_source
        and v in can_reach_sink
    ]

    frac_relevant_arcs = len(relevant_arcs) / G.number_of_edges()



    # Original source-sink shortest path
    try:
        # Minimum total traversal cost
        sp_length = nx.shortest_path_length(G, source=source, target=sink, weight="weight")

        # Minimum number of arcs, ignoring costs
        sp_edges = nx.shortest_path_length(G, source=source, target=sink)

        # Number of arcs along a minimum-cost path
        sp = nx.shortest_path(G, source=source, target=sink, weight="weight")

        weighted_sp_edges = len(sp) - 1

    except nx.NetworkXNoPath:
        sp_length = np.nan
        sp_edges = np.nan
        weighted_sp_edges = np.nan
        
    # Interdictability
    interdictable = sample.get("interdictable", [])
    
    if len(interdictable) > 0:
        n_interdictable = np.sum(interdictable)
        frac_interdictable = np.mean(interdictable)
    else:
        n_interdictable = np.nan
        frac_interdictable = np.nan

    num_shortest_paths = count_shortest_paths(G, source, sink, weight="weight")

    return {
        "dataset": dataset_name,
        "topology": sample.get("topology", dataset_name),

        "n_nodes": n,
        "n_arcs": m,
        "density": m / n,
        "graph_seed": sample.get("graph_seed", np.nan),

        "avg_in_degree": in_degrees.mean(),
        "avg_out_degree": out_degrees.mean(),
        "std_degree": total_degrees.std(),
        "max_degree": total_degrees.max(),

        "std_in_degree": std_in_degree,
        "std_out_degree": std_out_degree,
        "max_in_degree": max_in_degree,
        "max_out_degree": max_out_degree,

        "edge_connectivity": edge_connectivity,
        "n_relevant_arcs": len(relevant_arcs),
        "frac_relevant_arcs": frac_relevant_arcs,

        "shortest_path_length": sp_length,
        "shortest_path_edges": sp_edges,
        "weighted_sp_edges": weighted_sp_edges,
        
        "num_shortest_paths": num_shortest_paths,

        "n_interdictable": n_interdictable,
        "frac_interdictable": frac_interdictable,

        "attack_budget": sample.get(
            "attack_budget",
            sample.get("attack_limit", np.nan)),

        "mean_cost": np.mean(dist),
        "std_cost": np.std(dist),

        "mean_penalty": np.mean(sample["penalty"])
            if "penalty" in sample else np.nan,

        "optimal_interdicted_length": sample.get("path_length", np.nan)}

In [97]:
# Convert entire dataset

def summarize_dataset(data, dataset_name):

    rows = [graph_characteristics(sample, dataset_name) for sample in data]

    return pd.DataFrame(rows)

In [109]:
onein_train = load_json("training_data_shortest_path_onein_reps100.json")
mixed_60_train = load_json("training_data_shortest_path_mixed_60_10_reps100.json")
mixed_55_train = load_json("training_data_shortest_path_mixed_55_15_reps100.json")
one_in_filtered_train = load_json("training_data_shortest_path_onein_filtered.json")
mixed_filtered_train = load_json("training_data_shortest_path_mixed_filtered.json")


df_onein = summarize_dataset(onein_train, "One-In Training")
df_60 = summarize_dataset(mixed_60_train, "60/10 Mixed Training")
df_55 = summarize_dataset(mixed_55_train, "55/15 Mixed Training")
df_onein_filtered = summarize_dataset(one_in_filtered_train, "Filtered One-In")
df_mixed_filtered = summarize_dataset(mixed_filtered_train, "Filtered Mixed")

In [111]:
df_onein_unique = df_onein.drop_duplicates(subset=["graph_seed"])
df_60_unique = df_60.drop_duplicates(subset=["graph_seed"])
df_55_unique = df_55.drop_duplicates(subset=["graph_seed"])
df_onein_filtered_unique = df_onein_filtered.drop_duplicates(subset=["graph_seed"])
df_mixed_filtered_unique = df_mixed_filtered.drop_duplicates(subset=["graph_seed"])

In [115]:
topology_metrics = ["shortest_path_length","shortest_path_edges","weighted_sp_edges","num_shortest_paths","n_nodes","n_arcs", 
                    "std_in_degree","std_out_degree", "max_in_degree","max_out_degree","edge_connectivity","frac_relevant_arcs"]

topology_summary = (df_mixed_filtered_unique.groupby("topology")[topology_metrics].agg(["mean", "median", "min", "max"]))

topology_summary.round(3)

           shortest_path_length                       shortest_path_edges  \
                           mean  median    min    max                mean
topology
geometric                30.008  26.000  1.000  111.0               6.275
grid                      6.656   8.000  0.000   22.0               4.478
one_in                   25.295  21.500  3.000   79.0               5.628
real_world               29.293  12.395  1.453  162.0              13.794
star_mesh                11.242  11.000  3.000   21.0               3.000

                          weighted_sp_edges                num_shortest_paths  \
           median min max              mean median min max               mean
topology
geometric     5.0   1  19             6.850    6.0   1  20              1.250
grid          5.0   2   7             5.106    5.0   2  10              1.422
one_in        5.0   3  14             6.252    6.0   3  16              1.217
real_world   13.0   3  36            18.733   17.0   3  74              1.250
star_mesh     3.0   3   3             3.667    4.0   3   5              1.492

                           n_nodes                     n_arcs              \
           median min max     mean median min   max      mean  median min
topology
geometric     1.0   1   4   51.667   50.0  30    75   193.750   165.0  60
grid          1.0   1   5   51.667   50.0  30    75   193.750   165.0  60
one_in        1.0   1   4   51.667   50.0  30    75   193.750   165.0  60
real_world    1.0   1   8  719.500  931.5  24  1040  1913.667  2353.0  76
star_mesh     1.0   1   6   51.667   50.0  30    75   193.750   165.0  60

                 std_in_degree                       std_out_degree         \
             max          mean median    min     max           mean median
topology
geometric    450         1.717  1.679  0.849   3.493          1.809  1.722
grid         450         1.339  1.252  0.894   2.436          1.335  1.265
one_in       450         1.534  1.485  0.730   2.733          1.792  1.763
real_world  2950         1.196  1.152  0.745   2.015          1.196  1.148
star_mesh    450         5.568  5.165  1.653  12.508          7.366  7.050

                          max_in_degree                max_out_degree         \
              min     max          mean median min max           mean median
topology
geometric   0.849   3.615         7.717    7.0   4  13          7.775    7.0
grid        0.894   2.236         7.667    7.5   5  10          7.678    8.0
one_in      0.894   2.871         7.713    7.0   3  17          8.297    8.0
real_world  0.745   2.015         7.833    6.0   5  15          7.833    6.0
star_mesh   3.751  13.180        26.183   24.5   8  62         33.217   29.0

                   edge_connectivity                frac_relevant_arcs         \
           min max              mean median min max               mean median
topology
geometric    3  14             2.208    1.0   1   9              0.756  0.856
grid         5  11             7.000    7.0   5   9              1.000  1.000
one_in       4  15             1.745    1.0   1   8              0.935  0.975
real_world   5  15             2.006    2.0   1   5              0.998  1.000
star_mesh   14  68             1.667    2.0   1   2              0.879  0.933


              min  max
topology
geometric   0.056  1.0
grid        1.000  1.0
one_in      0.483  1.0
real_world  0.986  1.0
star_mesh   0.560  1.0

In [103]:
structural_metrics = [
    "shortest_path_edges",
    "std_in_degree",
    "std_out_degree",
    "max_in_degree",
    "max_out_degree",
    "edge_connectivity",
    "frac_relevant_arcs"
]

structural_summary = (
    df_60_unique
    .groupby("topology")[structural_metrics]
    .agg(["mean", "median", "min", "max"])
)

display(structural_summary.round(3))

          shortest_path_edges                std_in_degree                \
                         mean median min max          mean median    min
topology
geometric               6.225    6.0   1  21         1.704  1.659  0.816
grid                    4.483    5.0   2   7         1.350  1.260  0.931
layered                 1.975    2.0   1   4         2.612  2.449  1.077
one_in                  3.319    3.0   1  11         1.522  1.506  0.775
star_mesh               2.158    2.0   2   3         5.566  5.070  1.685

                  std_out_degree                       max_in_degree         \
              max           mean median    min     max          mean median
topology
geometric   3.416          1.799  1.732  0.775   3.327         7.708    7.0
grid        2.436          1.333  1.249  0.894   2.113         7.675    7.5
layered     5.459          3.264  3.076  1.774   5.385        10.525   10.0
one_in      2.733          1.786  1.772  0.856   2.828         7.781    7.0
star_mesh  12.343          7.373  7.001  4.017  13.143        26.183   23.0

                  max_out_degree                edge_connectivity             \
          min max           mean median min max              mean median min
topology
geometric   4  13          7.817    7.0   3  14             2.233    1.0   1
grid        5  10          7.667    8.0   5  10             7.000    7.0   5
layered     4  21         15.758   15.0  10  24             8.033    7.0   1
one_in      3  17          8.293    8.0   3  16             2.843    2.0   1
star_mesh   8  63         33.125   29.5  15  65             2.000    2.0   2

              frac_relevant_arcs
          max               mean median    min    max
topology
geometric   9              0.742  0.850  0.127  1.000
grid        9              1.000  1.000  1.000  1.000
layered    18              0.568  0.569  0.147  0.906
one_in     10              0.937  0.975  0.070  1.000
star_mesh   2              0.874  0.935  0.520  1.000

In [105]:
density_summary = (
    df_60_unique
    .groupby(["topology", "density"])[
        ["shortest_path_edges",
         "edge_connectivity",
         "frac_relevant_arcs"]
    ]
    .mean()
    .reset_index()
)

display(density_summary.round(3))

,topology,density,shortest_path_edges,edge_connectivity,frac_relevant_arcs
0,geometric,2.0,8.800,1.100,0.431
1,geometric,3.0,7.067,1.300,0.734
2,geometric,4.0,5.400,2.333,0.810
3,geometric,6.0,3.633,4.200,0.994
4,grid,2.0,4.667,7.000,1.000
5,grid,3.0,4.667,7.000,1.000
6,grid,4.0,4.667,7.000,1.000
7,grid,6.0,3.933,7.000,1.000
8,layered,2.0,2.600,3.300,0.397
9,layered,3.0,2.000,5.900,0.527
10,layered,4.0,1.833,9.067,0.603
11,layered,6.0,1.467,13.867,0.745
12,one_in,2.0,4.883,1.456,0.818
13,one_in,3.0,3.200,2.189,0.947
14,one_in,4.0,2.956,3.067,0.984
15,one_in,6.0,2.239,4.661,0.998
16,star_mesh,2.0,2.167,2.000,0.660
17,star_mesh,3.0,2.167,2.000,0.877
18,star_mesh,4.0,2.200,2.000,0.962
19,star_mesh,6.0,2.100,2.000,0.998

In [43]:
print(df_60_unique["topology"].value_counts())

topology
one_in       720
grid         120
geometric    120
star_mesh    120
layered      120
Name: count, dtype: int64

In [45]:
depth_counts = pd.crosstab(
    df_60_unique["topology"],
    pd.cut(
        df_60_unique["shortest_path_edges"],
        bins=[0, 5, 10, 15, 20, np.inf],
        labels=["1-5", "6-10", "11-15", "16-20", "21+"],
        include_lowest=True
    ),
    margins=True
)

display(depth_counts)

shortest_path_edges  1-5  6-10  11-15  16-20  21+   All
topology
geometric             53    43     18      5    1   120
grid                  64    56      0      0    0   120
layered              120     0      0      0    0   120
one_in               586   131      3      0    0   720
star_mesh            120     0      0      0    0   120
All                  943   230     21      5    1  1200

In [75]:
training_comparison = pd.concat([df_onein_unique, df_filtered_unique, df_60_unique, df_55_unique], ignore_index=True)

metrics = ["shortest_path_length", "shortest_path_edges", "num_shortest_paths", "n_nodes", "n_arcs"]

training_summary = (training_comparison.groupby("dataset")[metrics].agg(["mean", "median", "min", "max"]))

display(training_summary.round(3))

                     shortest_path_length                 shortest_path_edges  \
                                     mean median min  max                mean
dataset
55/15 Mixed Training               14.317   11.0   0  102               4.109
60/10 Mixed Training               14.753   11.0   0  102               4.037
Filtered One-In                    20.600   19.0   3   78               5.267
One-In Training                    15.533   13.0   1   65               3.841

                                    num_shortest_paths                n_nodes  \
                     median min max               mean median min max    mean
dataset
55/15 Mixed Training    3.0   1  22              1.241    1.0   1   5  51.667
60/10 Mixed Training    3.0   1  22              1.216    1.0   1   5  51.667
Filtered One-In         5.0   3  16              1.193    1.0   1   4  51.667
One-In Training         4.0   1  14              1.174    1.0   1   5  51.667

                                     n_arcs
                     median min max    mean median min  max
dataset
55/15 Mixed Training   50.0  30  75  193.75  165.0  60  450
60/10 Mixed Training   50.0  30  75  193.75  165.0  60  450
Filtered One-In        50.0  30  75  193.75  165.0  60  450
One-In Training        50.0  30  75  193.75  165.0  60  450

In [59]:
depth_bins = pd.cut(
    training_comparison["shortest_path_edges"],
    bins=[0, 5, 10, 15, 20, np.inf],
    labels=["1-5", "6-10", "11-15", "16-20", "21+"],
    include_lowest=True
)

depth_comparison = pd.crosstab(
    training_comparison["dataset"],
    depth_bins,
    margins=True
)

depth_comparison

shortest_path_edges    1-5  6-10  11-15  16-20  21+   All
dataset
55/15 Mixed Training   919   254     21      5    1  1200
60/10 Mixed Training   943   230     21      5    1  1200
Filtered One-In        391   201      7      1    0   600
One-In Training        992   204      4      0    0  1200
All                   3245   889     53     11    2  4200